"use client"

import { useState } from "react"
import { ArrowDownLeft, ArrowUpRight, CalendarDays, ChevronDown, CreditCard, LayoutDashboard, MoreHorizontal, Plus, Settings, Target, Wallet, Landmark, TrendingUp, CircleHelp } from "lucide-react"
import { Area, AreaChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts"

const expenses = [
  { name: "Vivienda", amount: 820, color: "#f2653c", progress: 68, detail: "Alquiler y servicios" },
  { name: "Préstamos", amount: 465, color: "#263c54", progress: 42, detail: "3 cuotas activas" },
  { name: "Alimentación", amount: 318, color: "#8b7bd8", progress: 55, detail: "Compra y restaurantes" },
  { name: "Transporte", amount: 126, color: "#62b9a4", progress: 28, detail: "Combustible y viajes" },
]
const chartData = [{month:"May",value:2100},{month:"Jun",value:2350},{month:"Jul",value:2200},{month:"Ago",value:2680},{month:"Sep",value:2550},{month:"Oct",value:3160}]
const pieData = expenses.map((item) => ({ name:item.name, value:item.amount, color:item.color }))
const money = (value:number) => new Intl.NumberFormat("es-AR", { style:"currency", currency:"ARS", maximumFractionDigits:0 }).format(value)

export default function Home() {
  const [active, setActive] = useState("Resumen")
  const [month, setMonth] = useState("Octubre 2024")
  return <main className="min-h-screen lg:flex">
    <aside className="hidden w-64 shrink-0 border-r border-[#e6e9ee] bg-white p-6 lg:flex lg:flex-col">
      <div className="mb-12 flex items-center gap-2"><div className="grid size-9 place-items-center rounded-xl bg-[#f2653c] text-white"><Wallet size={19}/></div><span className="font-display text-xl font-bold tracking-tight">finanz<span className="text-orange">app</span></span></div>
      <nav className="flex flex-col gap-2">{[{Icon:LayoutDashboard,label:"Resumen"},{Icon:CalendarDays,label:"Calendario"},{Icon:CreditCard,label:"Gastos"},{Icon:Landmark,label:"Préstamos"}].map(({Icon,label}) => <button key={label as string} onClick={()=>setActive(label as string)} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold transition ${active===label ? "bg-[#fff0ea] text-[#f2653c]" : "text-[#667085] hover:bg-[#f7f8fa]"}`}><Icon size={18}/>{label}</button>)}</nav>
      <div className="mt-auto flex flex-col gap-2"><button className="flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold text-[#667085]"><Settings size={18}/>Configuración</button><div className="mt-4 flex items-center gap-3 border-t border-[#e6e9ee] pt-5"><div className="grid size-9 place-items-center rounded-full bg-[#e9e4fb] text-sm font-bold text-[#6256a3]">JM</div><div><p className="text-sm font-bold">Julieta M.</p><p className="text-xs text-[#667085]">Plan personal</p></div></div></div>
    </aside>
    <div className="min-w-0 flex-1">
      <header className="flex items-center justify-between border-b border-[#e6e9ee] bg-white px-5 py-4 lg:px-10"><div className="flex items-center gap-2 lg:hidden"><div className="grid size-8 place-items-center rounded-lg bg-[#f2653c] text-white"><Wallet size={17}/></div><span className="font-display font-bold">finanz<span className="text-orange">app</span></span></div><div className="hidden text-sm text-[#667085] lg:block">Miércoles, 9 de octubre de 2024</div><div className="flex items-center gap-3"><button className="rounded-lg p-2 text-[#667085] hover:bg-[#f7f8fa]"><CircleHelp size={19}/></button><div className="grid size-8 place-items-center rounded-full bg-[#e9e4fb] text-xs font-bold text-[#6256a3]">JM</div></div></header>
      <div className="mx-auto max-w-[1400px] p-5 lg:p-10"><div className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-sm font-semibold text-[#f2653c]">Tu salud financiera</p><h1 className="font-display text-3xl font-bold tracking-tight text-[#172333] lg:text-4xl">Resumen mensual</h1><p className="mt-2 text-sm text-[#667085]">Una vista clara de cómo se mueve tu dinero.</p></div><button className="flex w-fit items-center gap-2 rounded-xl border border-[#e6e9ee] bg-white px-4 py-3 text-sm font-semibold shadow-sm"><CalendarDays size={17} className="text-[#f2653c]"/>{month}<ChevronDown size={15}/></button></div>
        <section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={<Wallet/>} label="Saldo disponible" value={money(18420)} note="+12.8% vs. mes anterior" color="orange"/><StatCard icon={<ArrowDownLeft/>} label="Gastos del mes" value={money(1720)} note="54% de tu presupuesto" color="peach"/><StatCard icon={<ArrowUpRight/>} label="Ingresos" value={money(4880)} note="+8.4% vs. mes anterior" color="mint"/><StatCard icon={<Target/>} label="Ahorro proyectado" value={money(3160)} note="Objetivo: $3.500" color="lavender"/></section>
        <section className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><div className="card p-5 lg:p-7"><div className="mb-7 flex items-start justify-between"><div><h2 className="font-display text-lg font-bold">Flujo de dinero</h2><p className="mt-1 text-sm text-[#667085]">Evolución de tu saldo en los últimos meses</p></div><button className="rounded-lg p-2 text-[#667085] hover:bg-[#f7f8fa]"><MoreHorizontal size={20}/></button></div><div className="h-64 w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f2653c" stopOpacity={.28}/><stop offset="100%" stopColor="#f2653c" stopOpacity={0}/></linearGradient></defs><Tooltip formatter={(v) => money(Number(v))} contentStyle={{borderRadius:12,border:"1px solid #e6e9ee",fontSize:12}}/><Area type="monotone" dataKey="value" stroke="#f2653c" strokeWidth={3} fill="url(#area)"/></AreaChart></ResponsiveContainer></div><div className="mt-5 flex items-center gap-5 text-xs text-[#667085]"><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-[#f2653c]"/>Saldo acumulado</span><span>Última actualización hoy</span></div></div>
        <div className="card p-5 lg:p-7"><div className="flex items-start justify-between"><div><h2 className="font-display text-lg font-bold">Distribución de gastos</h2><p className="mt-1 text-sm text-[#667085]">Total comprometido este mes</p></div><button className="text-sm font-semibold text-[#f2653c]">Ver todo</button></div><div className="relative mx-auto my-5 size-52"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pieData} innerRadius={66} outerRadius={91} paddingAngle={3} dataKey="value" stroke="none">{pieData.map((entry)=><Cell key={entry.name} fill={entry.color}/>)}</Pie></PieChart></ResponsiveContainer><div className="absolute inset-0 grid place-items-center text-center"><div><p className="text-xs text-[#667085]">Total gastos</p><p className="font-display text-2xl font-bold">{money(1729)}</p></div></div></div><div className="grid grid-cols-2 gap-x-4 gap-y-3">{expenses.map((expense)=><div key={expense.name} className="flex items-center justify-between text-xs"><span className="flex items-center gap-2 text-[#667085]"><i className="size-2 rounded-full" style={{background:expense.color}}/>{expense.name}</span><strong>{Math.round(expense.amount/1729*100)}%</strong></div>)}</div></div></section>
        <section className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_1fr]"><div className="card overflow-hidden"><div className="flex items-center justify-between border-b border-[#e6e9ee] p-5 lg:px-7"><div><h2 className="font-display text-lg font-bold">Gastos del mes</h2><p className="mt-1 text-sm text-[#667085]">Lo que ya salió de tu bolsillo</p></div><button className="grid size-9 place-items-center rounded-xl bg-[#f2653c] text-white shadow-sm"><Plus size={18}/></button></div><div className="divide-y divide-[#e6e9ee]">{expenses.map((expense)=><div key={expense.name} className="flex items-center gap-3 px-5 py-4 lg:px-7"><div className="grid size-10 shrink-0 place-items-center rounded-xl" style={{background:`${expense.color}18`,color:expense.color}}><CreditCard size={18}/></div><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="truncate text-sm font-bold">{expense.name}</p><p className="text-sm font-bold">{money(expense.amount)}</p></div><p className="mt-1 text-xs text-[#667085]">{expense.detail}</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#f0f1f3]"><div className="h-full rounded-full" style={{width:`${expense.progress}%`,background:expense.color}}/></div></div></div>)}</div></div><div className="card p-5 lg:p-7"><div className="mb-6 flex items-start justify-between"><div><h2 className="font-display text-lg font-bold">Próximos vencimientos</h2><p className="mt-1 text-sm text-[#667085]">No dejes nada para último momento</p></div><button className="text-sm font-semibold text-[#f2653c]">Ver calendario</button></div><div className="flex flex-col gap-4"><Due date="12 OCT" title="Tarjeta de crédito" subtitle="Vencimiento en 3 días" amount="$ 235.000"/><Due date="15 OCT" title="Préstamo personal" subtitle="Cuota 8 de 24" amount="$ 180.500"/><Due date="30 OCT" title="Alquiler" subtitle="Vencimiento en 21 días" amount="$ 420.000"/></div></div></section>
        <div className="mt-6 flex items-center justify-between rounded-2xl border border-[#f5d4c9] bg-[#fff7f4] p-4 text-sm"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-white text-[#f2653c]"><TrendingUp size={18}/></div><p><strong>Vas muy bien.</strong> Este mes llevas un 18% más de ahorro que el anterior.</p></div><button className="hidden text-[#f2653c] sm:block">Ver análisis</button></div>
      </div><nav className="fixed bottom-0 left-0 right-0 z-10 flex justify-around border-t border-[#e6e9ee] bg-white px-3 py-3 lg:hidden">{[{Icon:LayoutDashboard,label:"Resumen"},{Icon:CalendarDays,label:"Calendario"},{Icon:CreditCard,label:"Gastos"},{Icon:Landmark,label:"Préstamos"},{Icon:Settings,label:"Más"}].map(({Icon,label})=><button key={label as string} onClick={()=>setActive(label as string)} className={`flex flex-col items-center gap-1 px-2 text-[10px] font-semibold ${active===label?"text-[#f2653c]":"text-[#667085]"}`}><Icon size={18}/>{label}</button>)}</nav>
    </div></main>
}
function StatCard({icon,label,value,note,color}:{icon:React.ReactNode,label:string,value:string,note:string,color:string}){return <div className="card p-5"><div className="mb-5 flex items-center justify-between"><div className={`grid size-10 place-items-center rounded-xl ${color==="orange"?"bg-[#fff0ea] text-[#f2653c]":color==="peach"?"bg-[#fff0ea] text-[#f2653c]":color==="mint"?"bg-[#d9f4ec] text-[#398d78]":"bg-[#e9e4fb] text-[#6256a3]"}`}>{icon}</div><span className="text-xs font-semibold text-[#398d78]">+8.4%</span></div><p className="text-sm text-[#667085]">{label}</p><p className="mt-1 font-display text-2xl font-bold">{value}</p><p className="mt-2 text-xs text-[#667085]">{note}</p></div>}
function Due({date,title,subtitle,amount}:{date:string,title:string,subtitle:string,amount:string}){return <div className="flex items-center gap-3"><div className="w-12 rounded-xl bg-[#f7f8fa] px-1 py-2 text-center"><p className="text-[10px] font-bold text-[#f2653c]">{date.split(" ")[1]}</p><p className="text-[10px] font-semibold text-[#667085]">{date.split(" ")[0]}</p></div><div className="min-w-0 flex-1"><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs text-[#667085]">{subtitle}</p></div><p className="text-sm font-bold">{amount}</p></div>}
